rabbitmq:
  host: localhost
  port: 5672
  username: admin
  password: admin123!@#
  exchange: raspberry.exchange
  raspberry-queue: raspberry.queue
  raspberry-key: raspberry.key
  image-queue: image.queue
  image-key: image.key
